"""Deterministic limits for Social Listening Phase 1."""
from __future__ import annotations

MAX_PROJECTS_PER_TENANT = 50
MAX_SUBJECTS_PER_PROJECT = 100
MAX_QUERIES_PER_PROJECT = 100
MAX_SOURCES_PER_PROJECT = 20
MAX_ALIASES_PER_SUBJECT = 40
MAX_INCLUDE_TERMS_PER_QUERY = 40
MAX_EXCLUDE_TERMS_PER_QUERY = 40
MAX_ITEMS_PER_INGESTION_RUN = 500
MAX_IMPORT_PAYLOAD_BYTES = 512_000
MAX_CONTENT_TEXT_CHARS = 8_000
MAX_EXCERPT_CHARS = 1_000
MAX_LIST_LIMIT = 100
DEFAULT_LIST_LIMIT = 25
MAX_IMPORT_REQUESTS_PER_TENANT_PER_HOUR = 30

# Freshness thresholds (seconds) for configured sources after last success.
FRESH_MAX_AGE_SECONDS = 6 * 3600
AGING_MAX_AGE_SECONDS = 24 * 3600

__all__ = [
    "MAX_PROJECTS_PER_TENANT",
    "MAX_SUBJECTS_PER_PROJECT",
    "MAX_QUERIES_PER_PROJECT",
    "MAX_SOURCES_PER_PROJECT",
    "MAX_ALIASES_PER_SUBJECT",
    "MAX_INCLUDE_TERMS_PER_QUERY",
    "MAX_EXCLUDE_TERMS_PER_QUERY",
    "MAX_ITEMS_PER_INGESTION_RUN",
    "MAX_IMPORT_PAYLOAD_BYTES",
    "MAX_CONTENT_TEXT_CHARS",
    "MAX_EXCERPT_CHARS",
    "MAX_LIST_LIMIT",
    "DEFAULT_LIST_LIMIT",
    "MAX_IMPORT_REQUESTS_PER_TENANT_PER_HOUR",
    "FRESH_MAX_AGE_SECONDS",
    "AGING_MAX_AGE_SECONDS",
]
