-- Frozen baseline schema for revision 20260521_initial_schema
-- Generated by scripts/generate_baseline_schema.py; do not edit by hand.
-- Reconstruction: head schema minus objects created/added by later Alembic revisions.

CREATE TABLE IF NOT EXISTS "clients" (
    "id" UUID NOT NULL,
    "company_name" VARCHAR(255) NOT NULL,
    "source_language" VARCHAR(10) NOT NULL,
    "business_category" VARCHAR(100) NOT NULL,
    "content_style" VARCHAR(100) NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    "notes" VARCHAR(1000),
    "telegram_id" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
    "telegram_publish_chat_id" VARCHAR(255),
    "telegram_publish_title" VARCHAR(255),
    "telegram_publish_type" VARCHAR(20),
    PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS ix_clients_telegram_id ON "clients" ("telegram_id");

CREATE TABLE IF NOT EXISTS "media_files" (
    "id" UUID NOT NULL,
    "client_id" UUID NOT NULL,
    "original_filename" VARCHAR(500) NOT NULL,
    "file_type" VARCHAR(10) NOT NULL,
    "mime_type" VARCHAR(100) NOT NULL,
    "storage_path" VARCHAR(1000) NOT NULL,
    "thumbnail_path" VARCHAR(1000),
    "file_size" BIGINT NOT NULL,
    "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "content_items" (
    "id" UUID NOT NULL,
    "client_id" UUID NOT NULL,
    "media_file_id" UUID,
    "platforms" VARCHAR[] NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    "source" VARCHAR(20) NOT NULL,
    "caption_short_ru" TEXT,
    "caption_short_uz" TEXT,
    "caption_short_en" TEXT,
    "caption_long_ru" TEXT,
    "caption_long_uz" TEXT,
    "caption_long_en" TEXT,
    "hashtags" TEXT,
    "internal_notes" TEXT,
    "scheduled_for" TIMESTAMP,
    "approved_at" TIMESTAMP,
    "published_at" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
    "client_review_preview_sent_at" TIMESTAMP,
    "client_review_preview_error" TEXT,
    PRIMARY KEY ("id"),
    FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON DELETE CASCADE,
    FOREIGN KEY ("media_file_id") REFERENCES "media_files" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "calendar_entries" (
    "id" UUID NOT NULL,
    "content_item_id" UUID NOT NULL,
    "scheduled_date" DATE NOT NULL,
    "time_slot" VARCHAR(10),
    "platforms" VARCHAR[] NOT NULL,
    "note" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    FOREIGN KEY ("content_item_id") REFERENCES "content_items" ("id") ON DELETE CASCADE,
    CONSTRAINT calendar_entries_content_item_id_key UNIQUE ("content_item_id")
);
CREATE UNIQUE INDEX IF NOT EXISTS calendar_entries_content_item_id_key ON "calendar_entries" ("content_item_id");
