"""Read-only page → endpoint → service → table dependency graph."""
from __future__ import annotations

from typing import Any

# Curated registry for developer diagnostics (not auto-generated).
PAGE_DEPENDENCIES: list[dict[str, Any]] = [
    {
        "page": "Dashboard",
        "route": "/dashboard",
        "endpoints": ["/api/v1/dashboard/overview"],
        "services": ["dashboard_service"],
        "tables": ["clients", "crm_leads", "crm_deals", "content_items", "operator_tasks", "publish_attempts"],
    },
    {
        "page": "CRM",
        "route": "/crm",
        "endpoints": ["/api/v1/crm/pipeline", "/api/v1/crm/leads"],
        "services": ["crm_service"],
        "tables": ["crm_leads", "crm_deals", "crm_proposals", "crm_documents", "clients", "partners", "attribution_links"],
    },
    {
        "page": "Sales Department",
        "route": "/sales-department",
        "endpoints": ["/api/v1/sales-department/dashboard"],
        "services": ["sales_department_dashboard_service", "dashboard_service", "crm_service", "revenue_service"],
        "tables": ["crm_leads", "crm_deals", "crm_proposals", "products", "partners", "attribution_links", "landing_pages"],
    },
    {
        "page": "Buyer Intelligence",
        "route": "/buyer-intelligence",
        "endpoints": [
            "/api/v1/buyer-intelligence/overview",
            "/api/v1/buyer-intelligence/buyers",
            "/api/v1/buyer-intelligence/top-buyers",
            "/api/v1/buyer-intelligence/risks",
            "/api/v1/buyer-intelligence/recalculate",
        ],
        "services": ["buyer_intelligence_service", "lead_classification_service", "communication_intelligence_service"],
        "tables": [
            "crm_leads",
            "crm_deals",
            "crm_activities",
            "proposal_documents",
            "communication_threads",
            "communication_messages",
            "revenue_events",
        ],
    },
    {
        "page": "Buyer Discovery",
        "route": "/buyer-discovery",
        "endpoints": [
            "/api/v1/buyer-discovery/overview",
            "/api/v1/buyer-discovery/buyers",
            "/api/v1/buyer-discovery/top-opportunities",
            "/api/v1/buyer-discovery/market-insights",
            "/api/v1/buyer-discovery/pipeline",
            "/api/v1/buyer-discovery/summary-widget",
            "/api/v1/buyer-discovery/executive-insights",
            "/api/v1/buyer-discovery/recalculate",
        ],
        "services": [
            "buyer_discovery_service",
            "buyer_intelligence_service",
            "deal_risk_service",
            "revenue_forecast_service",
        ],
        "tables": [
            "buyer_discovery_entries",
            "crm_leads",
            "crm_deals",
            "factory_platform_profiles",
            "communication_threads",
            "communication_messages",
        ],
    },
    {
        "page": "Buyer Network",
        "route": "/buyer-network",
        "endpoints": [
            "/api/v1/buyer-network/overview",
            "/api/v1/buyer-network/profiles",
            "/api/v1/buyer-network/relationships",
            "/api/v1/buyer-network/graph",
            "/api/v1/buyer-network/insights",
            "/api/v1/buyer-network/top-buyers",
            "/api/v1/buyer-network/summary-widget",
            "/api/v1/buyer-network/recalculate",
        ],
        "services": [
            "buyer_network_service",
            "buyer_discovery_service",
            "buyer_intelligence_service",
            "marketplace_service",
            "revenue_forecast_service",
        ],
        "tables": [
            "buyer_network_profiles",
            "buyer_relationships",
            "buyer_discovery_entries",
            "marketplace_opportunities",
            "tenants",
        ],
    },
    {
        "page": "Buyer Acquisition",
        "route": "/buyer-acquisition",
        "endpoints": [
            "/api/v1/buyer-acquisition/overview",
            "/api/v1/buyer-acquisition/buyers",
            "/api/v1/buyer-acquisition/opportunities",
            "/api/v1/buyer-acquisition/pipeline",
            "/api/v1/buyer-acquisition/insights",
            "/api/v1/buyer-acquisition/summary-widget",
        ],
        "services": [
            "buyer_acquisition_service",
            "buyer_discovery_service",
            "buyer_network_service",
            "buyer_intelligence_service",
            "marketplace_service",
        ],
        "tables": [
            "buyer_discovery_entries",
            "buyer_network_profiles",
            "buyer_relationships",
            "marketplace_opportunities",
            "crm_leads",
            "crm_deals",
        ],
    },
    {
        "page": "Revenue Engine",
        "route": "/revenue-engine",
        "endpoints": [
            "/api/v1/revenue-engine/overview",
            "/api/v1/revenue-engine/deals",
            "/api/v1/revenue-engine/pipeline",
            "/api/v1/revenue-engine/forecast",
            "/api/v1/revenue-engine/factories",
            "/api/v1/revenue-engine/opportunities",
            "/api/v1/revenue-engine/health",
            "/api/v1/revenue-engine/summary",
            "/api/v1/revenue-engine/actions",
            "/api/v1/revenue-engine/summary-widget",
            "/api/v1/revenue-engine/revenue-impact-panel",
            "/api/v1/revenue-engine/revenue-readiness-panel",
            "/api/v1/revenue-engine/revenue-performance-panel",
            "/api/v1/revenue-engine/refresh",
        ],
        "services": [
            "revenue_engine_service",
            "buyer_acquisition_engine_service",
            "real_factory_pilot_service",
            "tenant_service",
        ],
        "tables": [
            "crm_deals",
            "crm_leads",
            "clients",
        ],
    },
    {
        "page": "Buyer Acquisition Engine",
        "route": "/buyer-acquisition-engine",
        "endpoints": [
            "/api/v1/buyer-acquisition-engine/overview",
            "/api/v1/buyer-acquisition-engine/buyers",
            "/api/v1/buyer-acquisition-engine/matches",
            "/api/v1/buyer-acquisition-engine/pipeline",
            "/api/v1/buyer-acquisition-engine/opportunities",
            "/api/v1/buyer-acquisition-engine/summary",
            "/api/v1/buyer-acquisition-engine/actions",
            "/api/v1/buyer-acquisition-engine/summary-widget",
            "/api/v1/buyer-acquisition-engine/refresh",
        ],
        "services": [
            "buyer_acquisition_engine_service",
            "buyer_discovery_service",
            "buyer_intelligence_service",
            "buyer_network_service",
            "factory_profile_service",
        ],
        "tables": [
            "buyer_discovery_entries",
            "buyer_network_profiles",
            "buyer_relationships",
            "crm_leads",
            "crm_deals",
            "communication_contacts",
            "factory_platform_profiles",
            "factory_catalog_products",
            "factory_export_markets",
        ],
    },
    {
        "page": "Marketplace",
        "route": "/marketplace",
        "endpoints": [
            "/api/v1/marketplace/overview",
            "/api/v1/marketplace/opportunities",
            "/api/v1/marketplace/top-opportunities",
            "/api/v1/marketplace/insights",
            "/api/v1/marketplace/activity",
            "/api/v1/marketplace/create-opportunity",
            "/api/v1/marketplace/express-interest",
            "/api/v1/marketplace/claim-opportunity",
        ],
        "services": [
            "marketplace_service",
            "buyer_discovery_service",
            "buyer_intelligence_service",
            "deal_risk_service",
            "revenue_forecast_service",
        ],
        "tables": [
            "marketplace_opportunities",
            "marketplace_opportunity_views",
            "marketplace_opportunity_interests",
            "marketplace_opportunity_claims",
            "tenants",
        ],
    },
    {
        "page": "Deal Room v2",
        "route": "/deal-room",
        "endpoints": [
            "/api/v1/deal-room/v2/overview",
            "/api/v1/deal-room/v2/workspaces",
            "/api/v1/deal-room/v2/workspace/{room_id}",
            "/api/v1/deal-room/v2/summary-widget",
            "/api/v1/deal-room/v2/deal-acquisition-panel",
            "/api/v1/deal-room/v2/deal-revenue-panel",
            "/api/v1/deal-room/v2/refresh",
        ],
        "services": [
            "deal_room_v2_service",
            "deal_room_service",
            "buyer_acquisition_engine_service",
            "revenue_engine_service",
            "deal_risk_service",
            "buyer_intelligence_service",
        ],
        "tables": [
            "deal_rooms",
            "crm_deals",
            "crm_leads",
            "crm_documents",
            "crm_deal_events",
            "crm_activities",
            "proposal_documents",
            "factory_certificates",
            "revenue_events",
        ],
    },
    {
        "page": "Deal Risk",
        "route": "/deal-risk",
        "endpoints": [
            "/api/v1/deal-risk/overview",
            "/api/v1/deal-risk/deals",
            "/api/v1/deal-risk/high-risk",
            "/api/v1/deal-risk/opportunities",
            "/api/v1/deal-risk/recalculate",
        ],
        "services": [
            "deal_risk_service",
            "buyer_intelligence_service",
            "lead_classification_service",
            "communication_intelligence_service",
        ],
        "tables": [
            "crm_deals",
            "crm_leads",
            "proposal_documents",
            "communication_threads",
            "communication_messages",
            "operator_tasks",
        ],
    },
    {
        "page": "Revenue Forecast",
        "route": "/revenue-forecast",
        "endpoints": [
            "/api/v1/revenue-forecast/overview",
            "/api/v1/revenue-forecast/pipeline",
            "/api/v1/revenue-forecast/risks",
            "/api/v1/revenue-forecast/executive",
            "/api/v1/revenue-forecast/generate-forecast",
        ],
        "services": ["revenue_forecast_service", "sales_department_orchestrator"],
        "tables": ["crm_leads", "crm_deals", "proposal_documents"],
    },
    {
        "page": "Multi-Agent Sales Team",
        "route": "/multi-agent",
        "endpoints": [
            "/api/v1/multi-agent/overview",
            "/api/v1/multi-agent/agents",
            "/api/v1/multi-agent/recommendations",
            "/api/v1/multi-agent/health",
            "/api/v1/multi-agent/generate-briefing",
        ],
        "services": ["multi_agent_team_service", "sales_department_orchestrator"],
        "tables": [
            "crm_leads",
            "crm_deals",
            "deal_rooms",
            "communication_threads",
            "whatsapp_threads",
            "operator_tasks",
            "sales_workflow_recommendations",
        ],
    },
    {
        "page": "Sales Department v3",
        "route": "/sales-department-v3",
        "endpoints": [
            "/api/v1/sales-department-v3/overview",
            "/api/v1/sales-department-v3/priorities",
            "/api/v1/sales-department-v3/opportunities",
            "/api/v1/sales-department-v3/risks",
            "/api/v1/sales-department-v3/recommendations",
            "/api/v1/sales-department-v3/generate-briefing",
        ],
        "services": [
            "sales_department_orchestrator",
            "lead_intelligence_service",
            "communication_intelligence_service",
            "revenue_attribution_service",
            "sales_manager_service",
            "deal_room_service",
            "operator_task_engine_service",
            "sales_workflow_service",
            "executive_copilot_service",
        ],
        "tables": [
            "crm_leads",
            "crm_deals",
            "deal_rooms",
            "communication_threads",
            "whatsapp_threads",
            "operator_tasks",
            "sales_workflow_recommendations",
        ],
    },
    {
        "page": "Revenue",
        "route": "/revenue",
        "endpoints": ["/api/v1/revenue/overview"],
        "services": ["revenue_service"],
        "tables": ["crm_deals", "crm_leads", "attribution_links"],
    },
    {
        "page": "Revenue Attribution",
        "route": "/revenue-attribution",
        "endpoints": [
            "/api/v1/revenue-attribution/overview",
            "/api/v1/revenue-attribution/sources",
            "/api/v1/revenue-attribution/channels",
            "/api/v1/revenue-attribution/conversions",
            "/api/v1/revenue-attribution/insights",
            "/api/v1/revenue-attribution/recalculate",
        ],
        "services": ["revenue_attribution_service", "revenue_service", "attribution_link_service"],
        "tables": [
            "crm_deals",
            "crm_leads",
            "attribution_links",
            "proposal_documents",
            "communication_threads",
            "whatsapp_threads",
        ],
    },
    {
        "page": "Audit",
        "route": "/audit",
        "endpoints": ["/api/v1/audit/overview"],
        "services": ["audit_service"],
        "tables": ["content_items", "crm_leads", "crm_deals", "operator_tasks", "publish_attempts", "clients", "partners"],
    },
    {
        "page": "Sales Assistant",
        "route": "/sales-assistant",
        "endpoints": [
            "/api/v1/sales-assistant/recommendations",
            "/api/v1/sales-assistant/scan",
        ],
        "services": ["sales_assistant_service"],
        "tables": [
            "sales_assistant_recommendations",
            "crm_leads",
            "crm_deals",
            "communication_threads",
            "buyer_outreach_messages",
            "sales_playbooks",
        ],
    },
    {
        "page": "Lead Intelligence",
        "route": "/lead-intelligence",
        "endpoints": [
            "/api/v1/lead-intelligence/overview",
            "/api/v1/lead-intelligence/leads",
            "/api/v1/lead-intelligence/classify",
            "/api/v1/lead-intelligence/recalculate",
        ],
        "services": ["lead_classification_service", "communication_intelligence_service", "crm_service"],
        "tables": [
            "crm_leads",
            "crm_activities",
            "communication_threads",
            "communication_messages",
            "proposal_documents",
            "operator_tasks",
            "sales_assistant_recommendations",
        ],
    },
    {
        "page": "Communication Intelligence",
        "route": "/communication-intelligence",
        "endpoints": [
            "/api/v1/communication-intelligence/overview",
            "/api/v1/communication-intelligence/conversations",
            "/api/v1/communication-intelligence/analyze",
            "/api/v1/communication-intelligence/recalculate",
        ],
        "services": ["communication_intelligence_service", "crm_service"],
        "tables": [
            "communication_threads",
            "communication_messages",
            "communication_contacts",
            "whatsapp_threads",
            "whatsapp_messages",
            "crm_leads",
            "crm_deals",
            "proposal_documents",
        ],
    },
    {
        "page": "Workflows",
        "route": "/workflows",
        "endpoints": [
            "/api/v1/workflows/overview",
            "/api/v1/workflows/recommendations",
            "/api/v1/workflows/templates",
            "/api/v1/workflows/generate",
        ],
        "services": ["sales_workflow_service", "lead_classification_service", "operator_task_engine_service"],
        "tables": [
            "sales_workflow_recommendations",
            "crm_leads",
            "crm_proposals",
            "proposal_documents",
            "communication_threads",
            "operator_tasks",
        ],
    },
    {
        "page": "Sales Manager",
        "route": "/sales-manager",
        "endpoints": [
            "/api/v1/sales-manager/overview",
            "/api/v1/sales-manager/opportunities",
            "/api/v1/sales-manager/risks",
            "/api/v1/sales-manager/recommendations",
            "/api/v1/sales-manager/generate-briefing",
        ],
        "services": ["sales_manager_service", "lead_intelligence_service", "lead_classification_service", "communication_intelligence_service", "operator_task_engine_service", "sales_workflow_service"],
        "tables": [
            "crm_leads",
            "crm_deals",
            "crm_proposals",
            "proposal_documents",
            "communication_threads",
            "communication_messages",
            "whatsapp_threads",
            "whatsapp_messages",
            "operator_tasks",
            "sales_workflow_recommendations",
        ],
    },
    {
        "page": "WeChat Sync",
        "route": "/wechat-sync",
        "endpoints": [
            "/api/v1/wechat-sync/accounts",
            "/api/v1/wechat-sync/jobs",
            "/api/v1/wechat-sync/sync-contacts",
            "/api/v1/wechat-sync/sync-conversations",
            "/api/v1/wechat-sync/test-connection",
        ],
        "services": ["wechat_sync_service", "wechat_adapter"],
        "tables": [
            "wechat_sync_accounts",
            "wechat_sync_jobs",
            "communication_contacts",
            "communication_threads",
            "communication_messages",
            "crm_leads",
        ],
    },
    {
        "page": "WeChat Provider",
        "route": "/wechat-provider",
        "endpoints": [
            "/api/v1/wechat-provider/providers",
            "/api/v1/wechat-provider/configurations",
            "/api/v1/wechat-provider/health",
            "/api/v1/wechat-provider/test-connection",
            "/api/v1/wechat-provider/register-provider",
        ],
        "services": ["wechat_provider_service", "wechat_adapter"],
        "tables": [
            "wechat_providers",
            "wechat_provider_configurations",
            "wechat_provider_webhook_events",
        ],
    },
    {
        "page": "WhatsApp Sync",
        "route": "/whatsapp-sync",
        "endpoints": [
            "/api/v1/whatsapp-sync/accounts",
            "/api/v1/whatsapp-sync/jobs",
            "/api/v1/whatsapp-sync/sync-contacts",
            "/api/v1/whatsapp-sync/sync-conversations",
            "/api/v1/whatsapp-sync/test-connection",
        ],
        "services": ["whatsapp_sync_service", "whatsapp_adapter"],
        "tables": [
            "whatsapp_sync_accounts",
            "whatsapp_sync_jobs",
            "communication_contacts",
            "communication_threads",
            "communication_messages",
            "whatsapp_contacts",
            "whatsapp_threads",
            "whatsapp_messages",
            "crm_leads",
        ],
    },
    {
        "page": "WhatsApp Provider",
        "route": "/whatsapp-provider",
        "endpoints": [
            "/api/v1/whatsapp-provider/providers",
            "/api/v1/whatsapp-provider/configurations",
            "/api/v1/whatsapp-provider/health",
            "/api/v1/whatsapp-provider/test-connection",
            "/api/v1/whatsapp-provider/register-provider",
        ],
        "services": ["whatsapp_provider_service", "whatsapp_adapter"],
        "tables": [
            "whatsapp_providers",
            "whatsapp_provider_configurations",
            "whatsapp_provider_webhook_events",
        ],
    },
    {
        "page": "Unified Inbox",
        "route": "/unified-inbox",
        "endpoints": ["/api/v1/unified-inbox"],
        "services": ["unified_inbox_service", "sales_assistant_service", "communication_intelligence_service"],
        "tables": [
            "communication_threads",
            "communication_messages",
            "buyer_outreach_messages",
            "whatsapp_threads",
            "sales_assistant_recommendations",
        ],
    },
    {
        "page": "Inbox",
        "route": "/inbox",
        "endpoints": ["/api/v1/operator/inbox"],
        "services": ["operator_inbox_service", "operator_task_service"],
        "tables": ["telegram_group_buffer_messages", "content_items", "clients", "operator_tasks"],
    },
    {
        "page": "Tasks",
        "route": "/tasks",
        "endpoints": ["/api/v1/tasks"],
        "services": ["operator_task_service"],
        "tables": ["operator_tasks", "clients", "crm_leads"],
    },
    {
        "page": "Operator Tasks",
        "route": "/operator-tasks",
        "endpoints": [
            "/api/v1/operator-task-engine/tasks",
            "/api/v1/operator-task-engine/generate",
        ],
        "services": ["operator_task_engine_service", "sales_assistant_service", "unified_inbox_service"],
        "tables": [
            "operator_tasks",
            "sales_assistant_recommendations",
            "crm_leads",
            "crm_deals",
            "proposal_documents",
            "communication_threads",
        ],
    },
    {
        "page": "Communications",
        "route": "/communications",
        "endpoints": [
            "/api/v1/communications/dashboard",
            "/api/v1/communications/inbox",
            "/api/v1/communications/followups",
            "/api/v1/communications/templates",
            "/api/v1/communications/threads",
            "/api/v1/communications/contacts",
        ],
        "services": [
            "communication_hub_dashboard_service",
            "communication_followup_service",
            "communication_template_service",
            "communication_record_service",
            "communication_ai_hub_service",
            "communication_service",
        ],
        "tables": [
            "communication_threads",
            "communication_messages",
            "communication_contacts",
            "communication_follow_ups",
            "communication_message_templates",
            "crm_leads",
            "buyers",
            "sales_deals",
        ],
    },
    {
        "page": "Products",
        "route": "/products",
        "endpoints": ["/api/v1/products"],
        "services": ["product_service"],
        "tables": ["products", "clients"],
    },
    {
        "page": "Campaigns",
        "route": "/campaigns",
        "endpoints": ["/api/v1/campaigns"],
        "services": ["campaign_service"],
        "tables": ["campaigns", "clients", "content_items"],
    },
    {
        "page": "Media Library",
        "route": "/media-library",
        "endpoints": ["/api/v1/media-library"],
        "services": ["media_library_service"],
        "tables": ["media_assets", "clients", "campaigns"],
    },
    {
        "page": "Content",
        "route": "/content",
        "endpoints": ["/api/v1/content"],
        "services": ["content_service", "publish_service"],
        "tables": ["content_items", "clients", "publish_attempts"],
    },
    {
        "page": "Pipeline",
        "route": "/pipeline",
        "endpoints": ["/api/v1/content-pipeline/board"],
        "services": ["content_pipeline_service"],
        "tables": ["content_items", "campaigns", "clients"],
    },
    {
        "page": "Buyer Finder",
        "route": "/buyer-finder",
        "endpoints": ["/api/v1/buyer-finder/product/{id}"],
        "services": ["buyer_finder_service"],
        "tables": ["buyer_recommendations", "products", "crm_leads"],
    },
    {
        "page": "Export Agent",
        "route": "/export",
        "endpoints": ["/api/v1/export/dashboard"],
        "services": ["export_agent_service"],
        "tables": ["export_opportunities", "products", "crm_leads"],
    },
    {
        "page": "AI Command Center",
        "route": "/ai-command-center",
        "endpoints": ["/api/v1/ai-command/history"],
        "services": ["ai_command_service"],
        "tables": ["ai_commands"],
    },
    {
        "page": "Attribution Links",
        "route": "/attribution-links",
        "endpoints": ["/api/v1/attribution-links"],
        "services": ["attribution_link_service"],
        "tables": ["attribution_links", "clients"],
    },
    {
        "page": "Landing Pages",
        "route": "/landing-pages",
        "endpoints": ["/api/v1/landing-pages"],
        "services": ["landing_page_service"],
        "tables": ["landing_pages", "landing_leads", "clients"],
    },
    {
        "page": "Partners",
        "route": "/partners",
        "endpoints": ["/api/v1/partners"],
        "services": ["partner_service"],
        "tables": ["partners", "partner_networks"],
    },
    {
        "page": "Factory Partner Apply",
        "route": "/factory-apply",
        "endpoints": [
            "/api/v1/factory-partner/apply",
            "/api/v1/factory-partner/applications/{id}/submit",
        ],
        "services": ["factory_partner_portal_service"],
        "tables": ["factory_partner_applications"],
    },
    {
        "page": "Factory Partners Admin",
        "route": "/factory-partners",
        "endpoints": [
            "/api/v1/factory-partner/applications",
            "/api/v1/factory-partner/applications/{id}/approve",
            "/api/v1/factory-partner/applications/{id}/reject",
            "/api/v1/factory-partner/applications/{id}/create-client",
            "/api/v1/factory-partner/applications/{id}/create-portal-account",
        ],
        "services": ["factory_partner_portal_service", "customer_portal_service"],
        "tables": ["factory_partner_applications", "clients", "customer_portal_accounts"],
    },
    {
        "page": "Pilot Onboarding",
        "route": "/pilot-onboarding",
        "endpoints": [
            "/api/v1/pilot-onboarding/overview",
            "/api/v1/pilot-onboarding/applications",
            "/api/v1/pilot-onboarding/{id}",
            "/api/v1/pilot-onboarding/{id}/checklist",
            "/api/v1/pilot-onboarding/{id}/blockers",
            "/api/v1/pilot-onboarding/{id}/actions",
            "/api/v1/pilot-onboarding/{id}/refresh",
            "/api/v1/pilot-onboarding/summary-widget",
        ],
        "services": [
            "pilot_onboarding_service",
            "factory_partner_portal_service",
            "tenant_service",
            "subscription_service",
            "factory_profile_service",
            "customer_portal_service",
        ],
        "tables": [
            "factory_partner_applications",
            "tenants",
            "tenant_users",
            "clients",
            "customer_portal_accounts",
            "subscriptions",
            "factory_platform_profiles",
            "factory_catalog_products",
        ],
    },
    {
        "page": "Pilot Demo Mode",
        "route": "/pilot-demo-mode",
        "endpoints": [
            "/api/v1/pilot-demo-mode/overview",
            "/api/v1/pilot-demo-mode/actions/create_sample_brief",
            "/api/v1/pilot-demo-mode/actions/generate_sample_plan",
            "/api/v1/pilot-demo-mode/actions/approve_sample_plan",
            "/api/v1/pilot-demo-mode/actions/create_sample_tasks",
            "/api/v1/pilot-demo-mode/actions/simulate_publishing_pipeline",
            "/api/v1/pilot-demo-mode/actions/generate_sample_revenue_metrics",
            "/api/v1/pilot-demo-mode/reset",
        ],
        "services": ["pilot_demo_mode_service", "client_brief_service"],
        "tables": [
            "client_briefs",
            "content_items",
            "operator_tasks",
            "crm_leads",
            "crm_deals",
            "revenue_events",
        ],
    },
    {
        "page": "Pilot Demo",
        "route": "/pilot-demo",
        "endpoints": [
            "/api/v1/pilot-demo/overview",
            "/api/v1/pilot-demo/scenarios",
            "/api/v1/pilot-demo/factory-owner",
            "/api/v1/pilot-demo/executive",
            "/api/v1/pilot-demo/readiness",
            "/api/v1/pilot-demo/presentation-flow",
            "/api/v1/pilot-demo/refresh",
        ],
        "services": [
            "pilot_demo_service",
            "pilot_launch_service",
            "pilot_onboarding_service",
            "factory_profile_service",
            "buyer_acquisition_service",
            "marketplace_service",
            "revenue_forecast_service",
            "executive_copilot_service",
            "api_health_service",
        ],
        "tables": [
            "factory_partner_applications",
            "tenants",
            "tenant_users",
            "clients",
            "customer_portal_accounts",
            "subscriptions",
            "factory_platform_profiles",
            "buyer_discovery_entries",
            "marketplace_opportunities",
            "crm_leads",
            "crm_deals",
            "crm_proposals",
            "revenue_events",
        ],
    },
    {
        "page": "Pilot Launch Validation",
        "route": "/pilot-launch-validation",
        "endpoints": [
            "/api/v1/pilot-launch-validation/overview",
            "/api/v1/pilot-launch-validation/readiness",
            "/api/v1/pilot-launch-validation/admin-flow",
            "/api/v1/pilot-launch-validation/tenant-flow",
            "/api/v1/pilot-launch-validation/data-completeness",
            "/api/v1/pilot-launch-validation/client-facing-readiness",
            "/api/v1/pilot-launch-validation/blockers",
            "/api/v1/pilot-launch-validation/next-actions",
            "/api/v1/pilot-launch-validation/summary-widget",
            "/api/v1/pilot-launch-validation/refresh",
        ],
        "services": [
            "pilot_launch_validation_service",
            "pilot_execution_service",
            "pilot_sales_demo_service",
            "real_factory_pilot_service",
            "factory_profile_service",
            "buyer_acquisition_engine_service",
            "revenue_engine_service",
            "production_deployment_service",
            "executive_copilot_service",
            "api_health_service",
        ],
        "tables": [
            "factory_partner_applications",
            "tenants",
            "tenant_users",
            "clients",
            "admin_users",
            "factory_catalog_products",
            "factory_certificates",
            "factory_export_markets",
            "buyer_discovery_entries",
            "buyer_relationships",
            "marketplace_opportunities",
            "crm_leads",
            "crm_deals",
            "deal_rooms",
            "revenue_events",
        ],
    },
    {
        "page": "Pilot Sales Demo",
        "route": "/pilot-sales-demo",
        "endpoints": [
            "/api/v1/pilot-sales-demo/overview",
            "/api/v1/pilot-sales-demo/metrics",
            "/api/v1/pilot-sales-demo/factory-owner-story",
            "/api/v1/pilot-sales-demo/demo-flow",
            "/api/v1/pilot-sales-demo/summary-widget",
            "/api/v1/pilot-sales-demo/refresh",
        ],
        "services": [
            "pilot_sales_demo_service",
            "pilot_execution_service",
            "real_factory_pilot_service",
            "buyer_acquisition_engine_service",
            "revenue_engine_service",
            "deal_room_v2_service",
            "executive_copilot_service",
            "api_health_service",
        ],
        "tables": [
            "factory_partner_applications",
            "tenants",
            "tenant_users",
            "clients",
            "buyer_discovery_entries",
            "buyer_network_profiles",
            "buyer_relationships",
            "marketplace_opportunities",
            "crm_leads",
            "crm_deals",
            "deal_rooms",
            "revenue_events",
            "factory_platform_profiles",
        ],
    },
    {
        "page": "Pilot Launch",
        "route": "/pilot-launch",
        "endpoints": [
            "/api/v1/pilot-launch/overview",
            "/api/v1/pilot-launch/readiness",
            "/api/v1/pilot-launch/checklist",
            "/api/v1/pilot-launch/smoke-tests",
            "/api/v1/pilot-launch/seed-demo-data",
            "/api/v1/pilot-launch/run-qa",
        ],
        "services": [
            "pilot_launch_service",
            "pilot_onboarding_service",
            "first_pilot_client_service",
            "factory_partner_portal_service",
            "tenant_service",
            "subscription_service",
            "factory_profile_service",
            "customer_portal_service",
            "admin_security_service",
            "api_health_service",
        ],
        "tables": [
            "factory_partner_applications",
            "tenants",
            "tenant_users",
            "clients",
            "customer_portal_accounts",
            "subscriptions",
            "factory_platform_profiles",
            "factory_catalog_products",
            "factory_certificates",
            "factory_export_markets",
            "buyer_discovery_entries",
            "marketplace_opportunities",
            "crm_leads",
            "crm_deals",
            "crm_proposals",
            "revenue_events",
        ],
    },
    {
        "page": "First Pilot Client",
        "route": "/first-pilot-client",
        "endpoints": [
            "/api/v1/first-pilot-client/overview",
            "/api/v1/first-pilot-client/readiness",
            "/api/v1/first-pilot-client/blockers",
            "/api/v1/first-pilot-client/recommendations",
            "/api/v1/first-pilot-client/summary",
            "/api/v1/first-pilot-client/summary-widget",
            "/api/v1/first-pilot-client/refresh",
        ],
        "services": [
            "first_pilot_client_service",
            "pilot_onboarding_service",
            "factory_profile_service",
            "subscription_service",
            "customer_portal_service",
            "api_health_service",
            "executive_copilot_service",
        ],
        "tables": [
            "factory_partner_applications",
            "tenants",
            "tenant_users",
            "clients",
            "customer_portal_accounts",
            "subscriptions",
            "factory_platform_profiles",
            "factory_catalog_products",
            "factory_certificates",
            "factory_export_markets",
        ],
    },
    {
        "page": "Pilot Execution",
        "route": "/pilot-onboarding",
        "endpoints": [
            "/api/v1/pilot-execution/overview",
            "/api/v1/pilot-execution/report",
            "/api/v1/pilot-execution/seed-pilot-data",
            "/api/v1/pilot-execution/verify-pages",
        ],
        "services": [
            "pilot_execution_service",
            "real_factory_pilot_service",
            "first_pilot_client_service",
            "pilot_onboarding_service",
            "factory_profile_service",
            "buyer_acquisition_engine_service",
            "revenue_engine_service",
            "deal_room_v2_service",
            "executive_copilot_service",
            "api_health_service",
        ],
        "tables": [
            "factory_partner_applications",
            "tenants",
            "tenant_users",
            "clients",
            "customer_portal_accounts",
            "subscriptions",
            "factory_platform_profiles",
            "factory_catalog_products",
            "factory_certificates",
            "factory_export_markets",
            "factory_media_assets",
            "buyer_discovery_entries",
            "buyer_network_profiles",
            "buyer_relationships",
            "marketplace_opportunities",
            "crm_leads",
            "crm_deals",
            "deal_rooms",
            "revenue_events",
        ],
    },
    {
        "page": "Real Factory Pilot",
        "route": "/real-factory-pilot",
        "endpoints": [
            "/api/v1/real-factory-pilot/overview",
            "/api/v1/real-factory-pilot/checklist",
            "/api/v1/real-factory-pilot/blockers",
            "/api/v1/real-factory-pilot/actions",
            "/api/v1/real-factory-pilot/readiness",
            "/api/v1/real-factory-pilot/summary",
            "/api/v1/real-factory-pilot/summary-widget",
            "/api/v1/real-factory-pilot/candidate-indicator",
            "/api/v1/real-factory-pilot/refresh",
        ],
        "services": [
            "real_factory_pilot_service",
            "first_pilot_client_service",
            "pilot_onboarding_service",
            "production_deployment_service",
            "factory_profile_service",
            "subscription_service",
            "admin_security_service",
            "api_health_service",
            "executive_copilot_service",
        ],
        "tables": [
            "factory_partner_applications",
            "tenants",
            "tenant_users",
            "clients",
            "customer_portal_accounts",
            "subscriptions",
            "factory_platform_profiles",
            "factory_catalog_products",
            "factory_certificates",
            "factory_export_markets",
            "buyer_relationships",
            "marketplace_opportunity_interests",
            "marketplace_opportunity_claims",
        ],
    },
    {
        "page": "Production Deployment",
        "route": "/production-deployment",
        "endpoints": [
            "/api/v1/production-deployment/overview",
            "/api/v1/production-deployment/readiness",
            "/api/v1/production-deployment/environment",
            "/api/v1/production-deployment/checklist",
            "/api/v1/production-deployment/backups",
            "/api/v1/production-deployment/monitoring",
            "/api/v1/production-deployment/security",
            "/api/v1/production-deployment/summary",
            "/api/v1/production-deployment/summary-widget",
            "/api/v1/production-deployment/refresh",
        ],
        "services": [
            "production_deployment_service",
            "admin_security_service",
            "admin_rbac_service",
            "first_pilot_client_service",
            "subscription_service",
            "tenant_service",
            "api_health_service",
            "system_health_service",
            "executive_copilot_service",
        ],
        "tables": [
            "admin_users",
            "admin_sessions",
            "tenants",
            "subscriptions",
        ],
    },
    {
        "page": "Tenants",
        "route": "/tenants",
        "endpoints": [
            "/api/v1/tenants",
            "/api/v1/tenants/{id}",
            "/api/v1/tenants/{id}/users",
            "/api/v1/tenants/{id}/isolation-check",
            "/api/v1/factory-partner/applications/{id}/create-tenant",
        ],
        "services": ["tenant_service", "customer_portal_service", "factory_partner_portal_service"],
        "tables": ["tenants", "tenant_users", "clients", "customer_portal_accounts", "factory_partner_applications"],
    },
    {
        "page": "Customer Portal",
        "route": "/customer-portal",
        "endpoints": [
            "/api/v1/customer-portal/dashboard",
            "/api/v1/customer-portal/buyers",
            "/api/v1/customer-portal/deals",
            "/api/v1/customer-portal/proposals",
            "/api/v1/customer-portal/reports",
            "/api/v1/customer-portal/billing",
        ],
        "services": [
            "customer_portal_service",
            "subscription_service",
            "buyer_intelligence_service",
            "deal_risk_service",
            "revenue_attribution_service",
            "revenue_forecast_service",
        ],
        "tables": [
            "customer_portal_accounts",
            "clients",
            "crm_leads",
            "crm_deals",
            "proposal_documents",
            "revenue_events",
        ],
    },
    {
        "page": "Customer Portal v2",
        "route": "/customer-portal-v2",
        "endpoints": [
            "/api/v1/customer-portal-v2/dashboard",
            "/api/v1/customer-portal-v2/opportunities",
            "/api/v1/customer-portal-v2/deals",
            "/api/v1/customer-portal-v2/proposals",
            "/api/v1/customer-portal-v2/reports",
            "/api/v1/customer-portal-v2/billing",
            "/api/v1/customer-portal-v2/factory-snapshot",
            "/api/v1/customer-portal-v2/summary-widget",
        ],
        "services": [
            "customer_portal_v2_service",
            "customer_portal_service",
            "subscription_service",
            "buyer_intelligence_service",
            "buyer_acquisition_service",
            "marketplace_service",
            "buyer_network_service",
            "deal_risk_service",
            "revenue_attribution_service",
            "revenue_forecast_service",
            "factory_profile_service",
        ],
        "tables": [
            "tenants",
            "clients",
            "crm_leads",
            "crm_deals",
            "proposal_documents",
            "revenue_events",
            "factory_platform_profiles",
            "factory_catalog_products",
            "factory_certificates",
            "factory_export_markets",
            "subscriptions",
            "invoices",
        ],
    },
    {
        "page": "Factory Partner Platform",
        "route": "/factory-platform",
        "endpoints": [
            "/api/v1/factory-platform/dashboard",
            "/api/v1/factory-platform/company",
            "/api/v1/factory-platform/products",
            "/api/v1/factory-platform/reports",
            "/api/v1/factory-platform/insights",
            "/api/v1/factory-platform/workspaces",
            "/api/v1/factory-platform/profile",
            "/api/v1/factory-platform/catalog",
            "/api/v1/factory-platform/certificates",
            "/api/v1/factory-platform/export-markets",
            "/api/v1/factory-platform/performance",
            "/api/v1/factory-platform/profile-score",
            "/api/v1/factory-platform/verification-status",
            "/api/v1/factory-platform/summary-widget",
        ],
        "services": [
            "factory_platform_service",
            "factory_profile_service",
            "tenant_service",
            "buyer_intelligence_service",
            "buyer_acquisition_service",
            "deal_risk_service",
            "revenue_attribution_service",
            "revenue_forecast_service",
            "product_catalog_service",
            "subscription_service",
            "customer_portal_service",
            "marketplace_service",
        ],
        "tables": [
            "factory_platform_profiles",
            "factory_catalog_products",
            "factory_certificates",
            "factory_export_markets",
            "tenants",
            "clients",
            "products",
            "product_import_jobs",
            "crm_leads",
            "crm_deals",
            "proposal_documents",
            "factory_partner_applications",
            "customer_portal_accounts",
        ],
    },
    {
        "page": "Subscription Billing",
        "route": "/billing",
        "endpoints": [
            "/api/v1/billing/plans",
            "/api/v1/billing/subscriptions",
            "/api/v1/billing/invoices",
            "/api/v1/billing/usage",
            "/api/v1/billing/summary",
            "/api/v1/billing/summary-widget",
            "/api/v1/billing/create-subscription",
            "/api/v1/billing/activate",
            "/api/v1/billing/suspend",
            "/api/v1/billing/cancel",
        ],
        "services": ["subscription_service", "tenant_service"],
        "tables": ["plans", "subscriptions", "invoices", "tenants", "tenant_users", "crm_leads", "crm_deals"],
    },
    {
        "page": "Admin Users",
        "route": "/admin-users",
        "endpoints": [
            "/api/v1/admin-auth/users",
            "/api/v1/admin-auth/roles",
            "/api/v1/admin-auth/permissions",
            "/api/v1/admin-auth/sessions",
        ],
        "services": ["admin_auth_service", "admin_rbac_service"],
        "tables": ["admin_users", "admin_sessions", "admin_audit_logs"],
    },
    {
        "page": "Admin Audit",
        "route": "/admin-audit",
        "endpoints": [
            "/api/v1/admin-auth/audit-logs",
            "/api/v1/admin-auth/security-checks",
        ],
        "services": ["admin_rbac_service"],
        "tables": ["admin_audit_logs", "admin_users"],
    },
    {
        "page": "Admin Settings",
        "route": "/admin-settings",
        "endpoints": [
            "/api/v1/admin-auth/platform/tenants",
            "/api/v1/admin-auth/platform/billing",
            "/api/v1/admin-auth/platform/analytics",
            "/api/v1/system/dependencies",
        ],
        "services": ["admin_rbac_service", "subscription_service", "tenant_service"],
        "tables": ["admin_users", "tenants", "subscriptions", "plans"],
    },
    {
        "page": "Design System UI Health",
        "route": "/system",
        "endpoints": ["/api/v1/system/health", "/api/v1/system/dependencies"],
        "services": [],
        "tables": [],
    },
]


def dependency_graph() -> dict[str, Any]:
    chains: list[dict[str, Any]] = []
    for item in PAGE_DEPENDENCIES:
        chain: list[dict[str, str]] = [{"kind": "page", "name": item["page"]}]
        for ep in item["endpoints"]:
            chain.append({"kind": "endpoint", "name": ep})
        for svc in item["services"]:
            chain.append({"kind": "service", "name": svc})
        for tbl in item["tables"]:
            chain.append({"kind": "table", "name": tbl})
        chains.append({
            "page": item["page"],
            "route": item["route"],
            "endpoints": item["endpoints"],
            "services": item["services"],
            "tables": item["tables"],
            "chain": chain,
        })
    return {"pages": chains, "total": len(chains)}
